### ISSUE TITLE
如何删除faker3

### ISSUE THREAD

**Issue by NOwin111** [shufflewzc/faker2#101]
转到2了，然后青龙里删除了所有的3，但是没多久3就回来了。
请问如何把3删除

**Comment by shufflewzc** [comment]
拉库命令删除一下3



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dfbb9216 ***@***.***&gt;
发送时间: 2023年3月23日 20:30
收件人: shufflewzc/faker2 ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [shufflewzc/faker2] 如何删除faker3 (Issue #101)





 
转到2了，然后青龙里删除了所有的3，但是没多久3就回来了。
 请问如何把3删除
