### ISSUE TITLE
jd_check_dependent.py前置代理失效

### ISSUE THREAD

**Issue by ThingsWhy** [shufflewzc/faker2#108]
jd_check_dependent.py脚本的前置代理https://proxy.zyun.vip/应该已经失效了

**Comment by Lmzaxx** [comment]
已经失效了，自己替换就可以，https://gh.ddlc.top，https://gh.api.99988866.xyz/

**Comment by ThingsWhy** [comment]
> 已经失效了，自己替换就可以，[https://gh.ddlc.top，https://gh.api.99988866.xyz/](https://gh.ddlc.top%EF%BC%8Chttps://gh.api.99988866.xyz/)
不是替换的问题，主要是ql repo会自动更新这个脚本，过一段时间就会恢复为原脚本了

**Comment by Lmzaxx** [comment]
你直接黑名单添加这个脚本，让他不要更新
