### ISSUE TITLE
代码里可以不集成代理 https://proxy.zyun.vip 吗

### ISSUE THREAD

**Issue by bao3** [shufflewzc/faker2#113]
这个 URL 已经无法访问了，所以导致依赖检测脚本用不了
[jd_check_dependent.py](https://github.com/shufflewzc/faker2/blob/b749225a7a8678085e1799b502afcebbca85e99d/jd_check_dependent.py#L133)

这种联网的问题，交给用户来解决就好了，引用的代理会经常不能用的。

**Comment by shufflewzc** [comment]
此脚本已废弃
