### ISSUE TITLE
jd_identicalnew.py青龙2.12报错

### ISSUE THREAD

**Issue by vc5** [shufflewzc/faker2#12]
青龙版本：V2.12.0
https://github.com/shufflewzc/faker2/blob/975483770e55f6d4ac40126d08270d951470e85f/jd_identicalnew.py#L156-L159
建议引用以下文件中的函数https://github.com/shufflewzc/faker2/blob/975483770e55f6d4ac40126d08270d951470e85f/ql.js#L23-L25

**Comment by yanyuwangluo** [comment]
你提交pr吧

**Comment by vc5** [comment]
已提交PR #13，请审核

**Comment by yanyuwangluo** [comment]
> 已提交PR #13，请审核 

这个会影响11版本吗

**Comment by vc5** [comment]
兼容2.11

**Comment by yanyuwangluo** [comment]
已测试，2.11 2.12都可以完美使用。
