### ISSUE TITLE
农场一开始运行就报错

### ISSUE THREAD

**Issue by xiaozhigit** [shufflewzc/faker2#127]
![image](https://github.com/shufflewzc/faker2/assets/23021708/6dc8642f-6d9e-4560-9e3c-76ade2520ad8)
❌ 东东农场日常任务, 失败! 原因: TypeError: require(...).UARAM is not a function!

**Comment by shufflewzc** [comment]
UA文件错误，把Deps文件夹清空即可

**Comment by xiaozhigit** [comment]
还是不行呢

**Comment by xiaozhigit** [comment]
我linux 的依赖未安装和这个有关系嘛
