### ISSUE TITLE
种豆得豆报错

### ISSUE THREAD

**Issue by wodexiaobai322** [shufflewzc/faker2#130]
获取任务及基本信息

❗️种豆得豆, 错误!
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at /ql/data/scripts/shufflewzc_faker2_main/jd_plantBean.js:27:67351
    at got.post.then.message (/ql/data/scripts/shufflewzc_faker2_main/jd_plantBean.js:29:6792)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
undefined
种豆得豆-初始失败:  {"code":"1","echo":"required string parameter 'functionId' is not present"}

🔔种豆得豆, 结束! 🕛 6.066 秒

系统环境：ubuntu22.04 青龙v2.16.0 docker20.10.25
感谢！

**Comment by ghsssss** [comment]
删除python的ds依赖

**Comment by wodexiaobai322** [comment]
> 

原本就没加ds依赖😪

**Comment by piglingcn** [comment]
> 删除python的ds依赖

的确可以~~！报的SyntaxError: Invalid or unexpected token~删了ds脚本正常了。。。

**Comment by wodexiaobai322** [comment]
不知道为什么突然就好了，猜测可能是原先的ip被京东封禁，换了ip就没问题了
