### ISSUE TITLE
jd_DailyBonus_Mod执行失败！

### ISSUE THREAD

**Issue by 1264116203** [shufflewzc/faker2#149]
## 开始执行... 2023-10-25 14:57:24

开始检测【京东账号1】pass杰....

京东商城-京豆签到失败 

京东商城-超市签到失败 

京东商城-转盘签到失败 

京东商城-闪购签到失败 

京东现金-红包签到失败 

京东魔方-尝试查询活动(2) 

京东魔方-尝试查询活动(1) 

京东魔方-尝试查询活动(null) 

京东商城-魔方签到失败 

‼️京东商城-现金发生错误
‼️名称: TypeError
‼️描述: Cannot read properties of undefined (reading 'success')
‼️状态: 200
‼️响应: {"code":"2","echo":"the current API does not exist"}

京东商城-金贴签到失败 

京东商城-摇一摇签到失败 

京东秒杀-红包查询失败 

京东金贴-双签领取异常 

金融京豆-双签查询成功 

京东-总红包查询成功 

京东-总钢镚查询成功 

京东-总京豆查询成功 

京东-总现金查询失败 

京东-总金贴查询成功 

【签到概览】:  失败33个, 错误1个
【账号总计】:  566京豆
【其他总计】:  0.03金贴, 3.95红包

京东商城-京豆: 失败, 原因: 未知 ⚠️
京东商城-超市: 失败, 原因: 未知 ⚠️
京东金融-钢镚: 失败, 未获取签到Body ⚠️
京东商城-转盘: 失败, 原因: 未知 ⚠️
京东商城-闪购: 失败, 原因: 未知 ⚠️
京东现金-红包: 失败, 原因: 未知 ⚠️
京东商城-魔方: 失败, 原因: 无机会 ⚠️
京东商城-现金: 异常, 已输出日志 ‼️
京东商城-金贴: 失败, 原因: 未知 ⚠️
京东商城-摇摇: 失败, 原因: 未知 ⚠️
京东秒杀-红包: 失败, 暂无有效活动 ⚠️
京东金贴-双签: 失败, 原因: 领取异常 ⚠️
京东失眠-补贴: 失败, 需要手动执行 ⚠️
京东手机-小时: 失败, 需要手动执行 ⚠️
京东商城-卡包: 失败, 需要手动执行 ⚠️
京东商城-内衣: 失败, 需要手动执行 ⚠️
京东商城-电竞: 失败, 需要手动执行 ⚠️
京东商城-箱包: 失败, 需要手动执行 ⚠️
京东商城-服饰: 失败, 需要手动执行 ⚠️
京东商城-校园: 失败, 需要手动执行 ⚠️
京东商城-健康: 失败, 不含活动数据 ⚠️
京东商城-鞋靴: 失败, 需要手动执行 ⚠️
京东商城-童装: 失败, 需要手动执行 ⚠️
京东商城-母婴: 失败, 需要手动执行 ⚠️
京东商城-数码: 失败, 需要手动执行 ⚠️
京东商城-女装: 失败, 需要手动执行 ⚠️
京东商城-图书: 失败, 需要手动执行 ⚠️
京东拍拍-二手: 失败, 需要手动执行 ⚠️
京东商城-菜场: 失败, 需要手动执行 ⚠️
京东商城-陪伴: 失败, 需要手动执行 ⚠️
京东商城-清洁: 失败, 需要手动执行 ⚠️
京东商城-个护: 失败, 需要手动执行 ⚠️
京东商城-家电: 失败, 需要手动执行 ⚠️
金融京豆-双签: 失败, 原因: 已签过 ⚠️

**Comment by shufflewzc** [comment]
此脚本暂时失效
