### ISSUE TITLE
能否默认开启农场任务的通知？

### ISSUE THREAD

**Issue by Lionhart31502** [shufflewzc/faker2#154]
不知道从什么时候开始，农场任务都不通知了，助力池的任务还加密，每次手动改完普通任务的通知，一更新库就又回去了非常不方便。

能不能改回默认通知？

该通知的不通知，不该通知的重复任务检查瞎通知，一小时一次，也是醉了。

**Comment by shufflewzc** [comment]
一键脚本模板已更新开启通知变量
