### ISSUE TITLE
带图评价脚本获取不了待评价列表了

### ISSUE THREAD

**Issue by liam-chew** [shufflewzc/faker2#155]
即使待评价有50个多，运行脚本日志输出如下：

没有待评价!!
等待...

🔔带图评价, 结束! 🕛 28.045 秒

**Comment by shufflewzc** [comment]
我这里试了正常，你是不是搞错号了

**Comment by liam-chew** [comment]
真的，我就一个帐号，更新了下cookie还是不行。请问大佬还需要其他额外的设置吗

**Comment by liam-chew** [comment]
我看见手机网页版的京东我的主页那里并没有待评价这一栏，会不会和这个有关系...

**Comment by shufflewzc** [comment]
@fat-lion 有

**Comment by liam-chew** [comment]
有办法么？是更新脚本还是其他方式绕过去呢

**Comment by shufflewzc** [comment]
以app显示为准



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fat-lion ***@***.***&gt;
发送时间: 2023年11月22日 00:16
收件人: shufflewzc/faker2 ***@***.***&gt;
抄送: Faker ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [shufflewzc/faker2] 带图评价脚本获取不了待评价列表了 (Issue #155)





 
有办法么？是更新脚本还是其他方式绕过去呢

**Comment by shufflewzc** [comment]
已更新
