### ISSUE TITLE
带图评价显示403

### ISSUE THREAD

**Issue by zhangwenbing1985** [shufflewzc/faker2#157]
## 开始执行... 2023-12-01 08:17:01

🔔带图评价, 开始!

====================共2个京东账号Cookie=================

============脚本执行时间：2023/12/01 08:17:02=============

>>>>>>>>>>>>>>Faker提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>>>

♻️当前使用内置sign，控制变量SIGN_URL

******开始【京东账号1】jd_6b8*********

Response code 403 (Forbidden)
准备获取评价...
等待...

## 执行结束... 2023-12-01 08:17:25  耗时 24 秒

**Comment by liyan2015** [comment]
同样问题，换了IP也不行

**Comment by shufflewzc** [comment]
已更新 拉库即可
