### ISSUE TITLE
好几个js都报错，找不到模块 Cannot find module

### ISSUE THREAD

**Issue by luiguangguan** [shufflewzc/faker2#163]
京东美妆签到
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module './function/sign_graphics_validate.js'
Require stack:
- /ql/data/scripts/shufflewzc_faker2/jd_sign_graphics1.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/ql/data/scripts/shufflewzc_faker2/jd_sign_graphics1.js:8:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/shufflewzc_faker2/jd_sign_graphics1.js' ]
}

**Comment by shufflewzc** [comment]
@luiguangguan 拉库不完全，建议使用2.11.3拉库 或参考拉库教程

**Comment by luiguangguan** [comment]
@shufflewzc 我看目录中是有这个文件的/function/sign_graphics_validate.js

**Comment by shufflewzc** [comment]
@luiguangguan 那你检查下青龙版本吧

**Comment by luiguangguan** [comment]
行吧 我换旧版本试试

**Comment by luiguangguan** [comment]
2.11.3版本没有拉取仓库功能

**Comment by shufflewzc** [comment]
@luiguangguan https://thin-hill-428.notion.site/QL-pannel-Pull-GitHub-Repository-Code-da5099068a434e29920cdcb3e7af4410?pvs=4

**Comment by luiguangguan** [comment]
有没有列出脚本依赖的包，兼容那些版本，我看一些博主说的安装的一些依赖，没有写具体的版本，估计会直接安装最新版的包

**Comment by luiguangguan** [comment]
换了旧版本2.11.3，CPU一直满载

**Comment by luiguangguan** [comment]
## 解决方案
我早到原因了
按照旧版的拉库方法如下
拉库前请打开青龙面板-配置文件 第18行 GithubProxyUrl="" 双引号中的内容清空

复制以下拉库命令即可。

Faker2 助力池版【安全本地sign防CK泄漏】上车机器人 @chriszhuli_bot 
ql repo https://git.metauniverse-cn.com/https://github.com/shufflewzc/faker2.git "jd_|jx_|gua_|jddj_|jdCookie" "activity|backUp" "^jd[^_]|USER|function|utils|sendNotify|ZooFaker_Necklace.js|JDJRValidator_|sign_graphics_validate|ql|JDSignValidator|magic|depend|h5sts" "main"

Faker3 内部互助版【安全本地sign防CK泄漏】
ql repo https://git.metauniverse-cn.com/https://github.com/shufflewzc/faker3.git "jd_|jx_|gua_|jddj_|jdCookie" "activity|backUp" "^jd[^_]|USER|function|utils|sendNotify|ZooFaker_Necklace.js|JDJRValidator_|sign_graphics_validate|ql|JDSignValidator|magic|depend|h5sts" "main"

### 根据青龙面板的说明

ql repo <repo_url> <whitelist> <blacklist> <dependence> <branch> <extensions>
![image](https://github.com/shufflewzc/faker2/assets/20753694/28a2dc6f-a966-471b-adcb-c1b09585be40)


根据上面的参数 **仓库地址** **黑名单** **白名单** **依赖项** **git分支** 扩展配置

在新版的青龙面板中可以这样设置↓↓↓，我的版本是**V2.16.5**
![image](https://github.com/shufflewzc/faker2/assets/20753694/2d47bb88-8537-4e25-b7f8-85eab809026d)

**Comment by shufflewzc** [comment]
> 有没有列出脚本依赖的包，兼容那些版本，我看一些博主说的安装的一些依赖，没有写具体的版本，估计会直接安装最新版的包

有 请查看教程目录内依赖安装教程
