### ISSUE TITLE
脚本出错

### ISSUE THREAD

**Issue by jinde98** [shufflewzc/faker2#165]
我这里除了京豆签到脚本能用，其他脚本都出错了。

**Comment by luiguangguan** [comment]
至少应该贴出错误信息给开发者看

**Comment by jinde98** [comment]
![image](https://github.com/shufflewzc/faker2/assets/127750182/b59b5eb7-29e3-4508-a611-f1a8708cd010)
![image](https://github.com/shufflewzc/faker2/assets/127750182/dfb4f3a5-070a-4d3d-99e4-e79e8bb81540)
就是类似 这些，我截了两张图

**Comment by shufflewzc** [comment]
在依赖管理 Python下 删除ds

**Comment by jinde98** [comment]
感谢大佬的指点，已经正常运行了
