### ISSUE TITLE
通过 【新手推荐】青龙稳定版一键配置 部署 2.11.3版本青龙 由于 淘宝npm镜像服务证书到期，导致依赖安装失败

### ISSUE THREAD

**Issue by HeroPei96** [shufflewzc/faker2#175]
![image](https://github.com/shufflewzc/faker2/assets/23712702/b416c43e-ff4d-4f23-a296-784af50339b2)
如图这个该怎么解决

**Comment by shufflewzc** [comment]
docker exec -it qinglong bash
ls -a
vi .npmrc

先这么改 明天出个脚本替换

**Comment by shufflewzc** [comment]
搜索库内的jd_indeps.sh 也可以先安装基础依赖
