### ISSUE TITLE
脚本更新“踏春趣”这几个活动，都是4月前有效，怎么默认都是2025-1-1才执行呢？

### ISSUE THREAD

**Issue by jaxenDevelop** [shufflewzc/faker2#178]
<img width="1259" alt="截屏2024-03-27 13 58 13" src="https://github.com/shufflewzc/faker2/assets/35227327/40312191-68eb-48a2-be71-b45f5424db0c">
图片里是我手动运行了，开卡可以获得10个豆，但是好奇怎么默认都2025年执行，那会活动都没了吧，求教是我哪里没配置正确吗？

**Comment by shufflewzc** [comment]
@jaxenDevelop 为了保证利益，这类脚本不会自动执行，需要手动执行
