### ISSUE TITLE
spy无法更新订阅

### ISSUE THREAD

**Issue by jaxenDevelop** [shufflewzc/faker2#180]
大佬你好，我根据教程配置了auto_spy，前面所有流程都配好了，tg发送spy升级或者重启都可以正常运行，但发送“spy 更新 订阅”没有反应，查看终端中报错如下图，请教如何解决。
<img width="570" alt="截屏2024-04-06 14 46 24" src="https://github.com/shufflewzc/faker2/assets/35227327/4a13d96e-0d52-4bb6-a129-2116cd5ada07">

**Comment by shufflewzc** [comment]
@jaxenDevelop 是spy 订阅 更新
