### ISSUE TITLE
sendNotify.js推送wxpusher通知失败

### ISSUE THREAD

**Issue by jaxenDevelop** [shufflewzc/faker2#181]
大佬你好，仓库里的sendNotify.js推送一直失败，我自己替换成https://github.com/ccwav/QLScript2这个就可以正常发通知了。
对我来说主要问题是手动替换js后，没多久又被覆盖修改为仓库里的，请问下有考虑改一下sendNotify.js么？或者我禁用哪个脚本可以不会覆盖我修改过的sendNotify.js呢？

**Comment by shufflewzc** [comment]
@jaxenDevelop 你可以对比下，文件其实是一样的。你需要做的是把这个文件放到deps文件夹里

**Comment by jaxenDevelop** [comment]
> @jaxenDevelop 你可以对比下，文件其实是一样的。你需要做的是把这个文件放到deps文件夹里

抱歉看错了😂是我青龙的脚本不知道为什么被改成了这个，仓库里确实是对的
![IMG_5165](https://github.com/shufflewzc/faker2/assets/35227327/026737e3-5478-4fe6-b191-ebb5abf9562b)
