### ISSUE TITLE
Spy监控的活动不能自动开卡吗

### ISSUE THREAD

**Issue by jaxenDevelop** [shufflewzc/faker2#184]
大佬你好，我整好了spy监控，可以自动添加环境变量和执行脚本，但是我看了下绝大部分的spy监控的活动都没有收益，主要是这些活动限制了必须关注店铺和开卡的会员才能参与，但是spy似乎不能自动给账号开卡？这个怎么解决呢？
![Uploading IMG_5200.png…]()

**Comment by shufflewzc** [comment]
@jaxenDevelop 脚本有开卡变量，可以设置

**Comment by jaxenDevelop** [comment]
> @jaxenDevelop 脚本有开卡变量，可以设置

明白了谢谢
