### ISSUE TITLE
获取 H5ST 失败

### ISSUE THREAD

**Issue by L4v3nder** [shufflewzc/faker2#222]
❌ 获取 H5ST 失败，错误信息：null
种豆得豆失败：required string parameter 'appid' is not present

请问有什么解决办法吗

**Comment by cpz2006** [comment]
我也是，从2024-10-18 15:15:00开始起，几乎所有的任务都是：
❌ 获取 H5ST 失败，错误信息：null
❓queryInteractiveInfo {"code":"1","echo":"required string parameter 'appid' is not present"}
或者
❌ 获取 H5ST 失败，错误信息：null
【账号1】XXX：进入首页失败：required string parameter 'functionId' is not present

**Comment by shufflewzc** [comment]
看TG群教程 自建h5st服务和sign服务

**Comment by wawmb** [comment]
牛逼
