### ISSUE TITLE
任务不执行，没有输出，没有报错

### ISSUE THREAD

**Issue by megumiss** [shufflewzc/faker2#223]
几乎所有的任务都是这样，什么也不跑
![image](https://github.com/user-attachments/assets/75c07b4c-86fc-44f3-90ec-13e9b20ab5fe)
![image](https://github.com/user-attachments/assets/7ba4722e-455b-4655-ac71-11f997c18398)

**Comment by checkToke** [comment]
环境变量中有包含github字符

**Comment by megumiss** [comment]
> 环境变量中有包含github字符

确实是。。
