### ISSUE TITLE
带图评价脚本用不了

### ISSUE THREAD

**Issue by chunkingzou** [shufflewzc/faker2#225]
============脚本执行时间：2024/11/02 22:05:47=============

>>>>>>>>>>>>>>Faker提醒您：有问题先更新 关注频道https://t.me/scriptalking>>>>>>>>>>>>>>>

♻️当前使用内置sign(推荐)，自定义变量SIGN_URL

/ql/shell/otask.sh: line 87:  1610 Illegal instruction     $timeoutCmd $which_program $file_param "${script_params[@]}"

**Comment by shufflewzc** [comment]
设置问题，如不清楚设置了什么建议青龙重新安装
