### ISSUE TITLE
jd_washbeans.js加密内部偷邀请

### ISSUE THREAD

**Issue by codingchenp** [shufflewzc/faker2#39]
async function _0xd068cc() {
    var _0x5d95ad = {
        'BLxUN': function _0x17f4e4(_0x2f898a, _0x1bfd65) {
            return _0x2f898a < _0x1bfd65;
        },
        'ekuEy': 'pVbNk9xIuI02DeRtwUiztA==',
        'IekkC': 's4UuZYFN6GW3jbg4x9Z8LA==',
        'RYnUE': 'Vf+kZwVHm4/P5/ZkyCY+DA==',
        'WuAub': '4y1yGPA4HCaFNCw8BZ6gsw==',
        'HpKXb': function _0xc8bbad(_0x652890, _0x2bd732, _0x13a1dc) {
            return _0x652890(_0x2bd732, _0x13a1dc);
        },
        'BkKSo': function _0x22e6f1(_0x44d89e, _0x48cb26, _0x4c651c) {
            return _0x44d89e(_0x48cb26, _0x4c651c);
        },
        'aXsBo': function _0x1af753(_0x5b675e, _0x32f300, _0x218f0a) {
            return _0x5b675e(_0x32f300, _0x218f0a);
        }
    };
    for (let _0x1adf32 = 0x0; _0x5d95ad['BLxUN'](_0x1adf32, _0x3c2585['length']); _0x1adf32++) {
        let _0x21f72e = [_0x5d95ad['ekuEy'], _0x5d95ad['IekkC'], _0x5d95ad['RYnUE'], _0x5d95ad['WuAub']];
        let _0x3f3d19 = _0x5d95ad['HpKXb'](_0x9ac67f, _0x21f72e, 0x1)[0x0];
        await _0x5d95ad['BkKSo'](_0x1c37e1, _0x3c2585[_0x1adf32], _0x3f3d19);
        await _0x5d95ad['BkKSo'](_0x41f002, _0x3c2585[_0x1adf32], _0x3f3d19);
        await _0x5d95ad['aXsBo'](_0x355ead, _0x3c2585[_0x1adf32], _0x3f3d19);
        await _0x5d95ad['aXsBo'](_0x392aa4, _0x3c2585[_0x1adf32], _0x3f3d19);
        await $['wait'](0x1f4);
    }
}

内部偷邀请人头，而且是偷所有的ck

**Comment by shufflewzc** [comment]
先下架 核查后再上
