### ISSUE TITLE
东东农场报错

### ISSUE THREAD

**Issue by nicklly** [shufflewzc/faker2#47]
当运行脚本时，处于1号的帐号基本是运行正常的，当2号、3号帐号开始执行时，执行到获取水滴时会提示如下
`TypeError: Cannot read properties of undefined (reading 'totalEnergy')
    at doTenWaterAgain (/ql/data/scripts/shufflewzc_faker2_main/jd_fruit.js:430:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async jdFruit (/ql/data/scripts/shufflewzc_faker2_main/jd_fruit.js:195:17)
    at async /ql/data/scripts/shufflewzc_faker2_main/jd_fruit.js:136:13`

参考之前的农场UA检测，我就有点怀疑是UA问题导致的，因为在使用助力池时会提示环境异常，提示如下
`开始助力好友
tonykun04716开始助力: 4c9f9f816d904a9c8ac39a1eba57e793
助力失败::{"code":"403","message":"运行环境异常，请您从正规渠道参与活动，稍后再试~"}`

结果后面就导致了获取不了farmUserPro里的数据

现在我在使用自己手机的UA，先跑一天看看是不是还是报同样的错

**Comment by shufflewzc** [comment]
好

**Comment by nicklly** [comment]
唔.... 已经跑4天了 可以鉴定为某东对UA检测更严格了

**Comment by xiangshang-kok** [comment]
> 

你好，请问一下脚本里的UA是在什么位置？以及要修改成什么内容？

**Comment by shufflewzc** [comment]
目前还是有随机出错的问题

**Comment by nicklly** [comment]
> 目前还是有随机出错的问题

或者把删除好友奖励去掉看看？我之前试过执行完这个脚本 就会提示数据异常 禁用脚本之后一直稳定跑到现在了

**Comment by shufflewzc** [comment]
已修复
