### ISSUE TITLE
助力群 TG群 现在是啥

### ISSUE THREAD

**Issue by LQ0611** [shufflewzc/faker2#48]
助力群 TG群 现在是啥，之前的是不是不能用了？

**Comment by shufflewzc** [comment]
Readme里面的频道，然后点讨论进群> 助力群 TG群 现在是啥，之前的是不是不能用了？

**Comment by LQ0611** [comment]
> 

我看到的两个分支里，’main‘分支Readme文件里，就 “readme” 文字， 另一个里面一堆 文字，
![image](https://user-images.githubusercontent.com/41603959/192762251-10b428f8-941a-4454-97b0-d6043fb569d4.png)

**Comment by shufflewzc** [comment]
https://t.me/Soucetalk
