### ISSUE TITLE
用一键脚本拉库的，提示缺h5sts.js

### ISSUE THREAD

**Issue by binidx** [shufflewzc/faker2#49]
faker 友情提示：您的脚本正常运行中
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './h5sts.js'

**Comment by shufflewzc** [comment]
旧版一键缺失了这个，到群里看最新的拉库地址手动添加任务拉一下就行

**Comment by TQG1997** [comment]
旧版的青龙缺失了这个吗，求加群方式
