### ISSUE TITLE
初始化农场数据异常

### ISSUE THREAD

**Issue by NeverAgain11** [shufflewzc/faker2#61]
东东农场助力池版

自动运行的时候会报异常然后结束任务。

初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常,农场初始化数据: {"code":"1","echo":"required string parameter 'functionId' is not present"}

但是手动运行的时候任务可以正常执行完全部步骤。
该怎么解决？

**Comment by shufflewzc** [comment]
APP打开 然后稍后运行
