### ISSUE TITLE
汪汪赛跑不能跑了

### ISSUE THREAD

**Issue by charleschangz** [shufflewzc/faker2#69]
Error TypeError: Cannot read properties of undefined (reading 'runningHomeInfo')
    at /ql/data/scripts/faker2/jd_joy_park_run.ts:89:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

都是这个错误，是不是改版了

**Comment by shufflewzc** [comment]
我看看

**Comment by charleschangz** [comment]
等你的好消息

**Comment by charleschangz** [comment]
> 我看看

等你好消息

**Comment by shufflewzc** [comment]
已更新汪汪赛跑
