### ISSUE TITLE
jd_work_validate.js这个脚本一跑机器占用就满了

### ISSUE THREAD

**Issue by firkerword** [shufflewzc/faker2#70]
环境是x86 qinglong2.11.3，不太了解这个脚本的作用，占用资源太大了，机器直接卡死

**Comment by shufflewzc** [comment]
export jd_work_validate_limit=1

**Comment by shufflewzc** [comment]
不过好像作用不大，删除了本脚本

**Comment by firkerword** [comment]
> 不过好像作用不大，删除了本脚本

好的 感谢大佬
