### ISSUE TITLE
自动评价失败

### ISSUE THREAD

**Issue by goblink7** [shufflewzc/faker2#74]
read ECONNRESET

❌ 自动评价, 失败! 原因: TypeError: Cannot read properties of undefined (reading 'maxPage')!

🔔自动评价, 结束! 🕛 1.053 秒

## 执行结束... 2022-12-13 20:06:00  耗时 2 秒

请问大佬，要怎么解决呀

**Comment by shufflewzc** [comment]
这种是号没有待评价，或者脚本出错了
