### ISSUE TITLE
东东农场任务也是报错，在手机上能打开

### ISSUE THREAD

**Issue by ltaa123** [shufflewzc/faker2#89]
![image](https://user-images.githubusercontent.com/42996583/215314814-eea64513-f7e5-4f5b-955b-5719f03a3802.png)

**Comment by shufflewzc** [comment]
有另外一个版本的农场，可以试试

**Comment by ltaa123** [comment]
请问什么版本呢  我用的faker2助力池版本 @shufflewzc
