### ISSUE TITLE
中文Cookie问题

### ISSUE THREAD

**Issue by PACEJJ27** [shufflewzc/faker2#94]
因为之前注册的账号是带中文的，所以获取到的pt_bin的值也是带中文，试过了纯英文的cookie请求没问题，带中文的就不行，能不能加一下处理中文的代码，谢谢！

**Comment by mjnhmd** [comment]
可以把cookie用未转码的 比如你浏览器里看到的应该是这样的
<img width="188" alt="image" src="https://user-images.githubusercontent.com/17866590/221789965-5b8895a2-20da-42d0-9a96-24ec4d53234b.png">，就直接填这个 别转成中文

**Comment by shufflewzc** [comment]
ptpin可以自行修改，不碍事
