### ISSUE TITLE
这是什么问题？原来都没出现，重新填写也没有用

### ISSUE THREAD

**Issue by 36EMiyuki** [shufflewzc/faker2#97]
提示:京东cookie 【pt_key=AAJj_5nbADAurrno_Ag-4n6aUXsyYVbAPilL_NnpVgo8bDj9GSAW9iQ26Ke3vZztXdfLnewnSO0;pt_pin=%E5%AF%85%E5%B0%8F%E9%A2%A8】填写不规范,可能会影响部分脚本正常使用。正确格式为: pt_key=xxx;pt_pin=xxx;（分号;不可少）

**Comment by amm10090** [comment]
pt_pin不对啊

**Comment by shufflewzc** [comment]
pin可以随便写 不影响
